name: Skaffold
description: Publish image 
branding:
  icon: upload-cloud
  color: blue
runs:
  using: 'docker'
  image: 'Dockerfile'

inputs:
  registry:
    description: The OCI registry to push to
  username:
    description: The username for accessing OCI registry
  password:
    description: The password for accessing OCI registry
